# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Events"
  url = ""
  weight = 20
  identifier = "events"

[[main]]
  name = "Types of Events"
  url = "events#types"
  weight = 21
  parent = "events"

[[main]]
  name = "Current Events"
  url = "events#current"
  weight = 22
  parent = "events"

[[main]]
  name = "Past Events"
  url = "events#past"
  weight = 23
  parent = "events"

[[main]]
  name = "Common Reading"
  url = "events#common-reading"
  weight = 24
  parent = "events"


[[main]]
  name = "Women"
  url = ""
  weight = 30
  identifier = "women"

[[main]]
  name = "Leadership"
  url = "women#leadership"
  weight = 31
  parent = "women"

[[main]]
  name = "Alumnae"
  url = "alumnae"
  weight = 32
  parent = "women"


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
