# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Events"
  url = "eventshome#events-types"
  weight = 20
  identifier = "eventshome"

[[main]]
  name = "Current Events"
  url = "eventshome#current"
  weight = 21
  parent = "eventshome"

[[main]]
  name = "Past Events"
  url = "eventshome#events"
  weight = 22
  parent = "eventshome"

[[main]]
  name = "Common Reading"
  url = "eventshome#common-reading"
  weight = 23
  parent = "eventshome"


[[main]]
  name = "People"
  url = "#people"
  weight = 30


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
